export enum HomeworkError {
  STUDENTS = 'Estudiantes erroneos',
  CLASSROOM = 'Salones erroneos',
  TOPICS = 'Temas erroneos',
  COLOR = 'Color erroneo',
  TEACHER = 'Profesor erroneo',
  COURSE = 'Curso erroneo',
  EXCERCISES = 'Ejercicios incorrectos',
  SCHOOL = 'Colegio erroneo',
  GRADE = 'Grado erroneo',
  SECTION = 'Seccion erronea',
  LEVEL = 'Nivel erroneo',
  INSIGNIA = 'Insignia erronea',
  CLASSROOM_ID = 'Id de salon invalido',
  STUDENT_ID = 'Id de estudiante invalido',
  AUTHOR = 'Autor inválido',
  COMMENT = 'Comentario inválido',
  DATE = 'Fecha inválida',
  NAME = 'Nombre inválido',
  HOMEWORK = 'Tarea inválido',
  DURATION = 'Duracion inválida',
  START_DATE = 'Fecha de inicio inválida',
  ACTIVE = 'Active inválido',
}
