export * from './teacher.dto'
export * from './student.dto'
export * from './login-user.dto'
export * from './school.dto'
export * from './teacher-code.dto'
export * from './student-code.dto'
export * from './register-student.dto'
export * from './register-teacher.dto'
